services:
  - type: web
    name: ais-test
    env: php
    buildCommand: composer install
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: AIS-Test
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: ais-test
          property: host 